export const Img = {
  logo1: require('../../src/assets/onboarding1.png'),
  logo2: require('../../src/assets/onboarding2.png'),
  logo3: require('../../src/assets/onboarding3.png'),
  quotebox: require('../../src/assets/quotebox.png'),
  share: require('../../src/assets/share.png'),
  copy: require('../../src/assets/copy.png'),
  sadcircle: require('../../src/assets/sadcircle.png'),
  lifecircle: require('../../src/assets/lifecircle.png'),
  lovecircle: require('../../src/assets/lovecircle.png'),
  happycircle: require('../../src/assets/happycircle.png'),
  happycircle: require('../../src/assets/happycircle.png'),
  birdcircle: require('../../src/assets/birdcircle.png'),
  travelcircle: require('../../src/assets/travelcircle.png'),
  trustcircle: require('../../src/assets/trustcircle.png'),
  friendscircle: require('../../src/assets/friendscircle.png'),
  plus: require('../../src/assets/plus.png'),
  home: require('../../src/assets/home.png'),
  save: require('../../src/assets/save.png'),
  gallery: require('../../src/assets/gallery.png'),
  blackgallery: require('../../src/assets/blackgallery.png'),
  text: require('../../src/assets/text.png'),
  textblack: require('../../src/assets/textblack.png'),
  textblack: require('../../src/assets/textblack.png'),
  property: require('../../src/assets/property.png'),
  propertyblack: require('../../src/assets/propertyblack.png'),
  font: require('../../src/assets/font.png'),
  fontblack: require('../../src/assets/fontblack.png'),
  color: require('../../src/assets/color.png'),
  colorblack: require('../../src/assets/colorblack.png'),
  colorblack: require('../../src/assets/colorblack.png'),
  effect: require('../../src/assets/effect.png'),
  effectblack: require('../../src/assets/effectblack.png'),
  shadow: require('../../src/assets/shadow.png'),
  shadowblack: require('../../src/assets/shadowblack.png'),
  colorpicker: require('../../src/assets/colorpicker.png'),

  more: require('../../src/assets/more.png'),
  roadsample: require('../../src/assets/roadsample.png'),

  leftarrow: require('../../src/assets/leftarrow.png'),
  rightarrow: require('../../src/assets/rightarrow.png'),
  bottomlogo: require('../../src/assets/bottomlogo.png'),
  bottomlogo2: require('../../src/assets/bottomlogo2.png'),

  cancel: require('../../src/assets/cancel.png'),
  arrow: require('../../src/assets/arow.png'),
  undo: require('../../src/assets/undo.png'),

  done: require('../../src/assets/done.png'),
  delete: require('../../src/assets/delete.png'),
  decrease: require('../../src/assets/A-.png'),
  increase: require('../../src/assets/A+.png'),
  alignCenter: require('../../src/assets/alignCenter.png'),
  alignLeft: require('../../src/assets/alignLeft.png'),
  alignRight: require('../../src/assets/alignRight.png'),
  lineSpace1: require('../../src/assets/lineSpace1.png'),
  lineSpace2: require('../../src/assets/lineSpace2.png'),
  letterSpace1: require('../../src/assets/letterSpace1.png'),
  letterSpace2: require('../../src/assets/letterSpace2.png'),

  //Share
  whatsapp: require('../../src/assets/ws.png'),
  pinteresr: require('../../src/assets/pinteresr.png'),
  messanger: require('../../src/assets/messanger.png'),
  mail: require('../../src/assets/mail.png'),
  link: require('../../src/assets/link.png'),
  linkdin: require('../../src/assets/linkdin.png'),
  insta: require('../../src/assets/insta.png'),
  fb: require('../../src/assets/fb.png'),
  twitter: require('../../src/assets/twitter.png'),

  //Quote background
  bg1: require('../../src/assets/quotebg/1.png'),
  bg2: require('../../src/assets/quotebg/2.png'),
  bg3: require('../../src/assets/quotebg/3.png'),
  bg4: require('../../src/assets/quotebg/4.png'),
  bg5: require('../../src/assets/quotebg/5.png'),
  bg6: require('../../src/assets/quotebg/6.png'),

  //Quote
  openQuote: require('../../src/assets/quote.png'),
  closeQuote: require('../../src/assets/quote-1.png'),
};
